### ISSUE TITLE
appstore app compile error

### ISSUE THREAD

**Issue by leeeboo** [awtrix/AWTRIX2.0-Apps#10]
@Blueforcer I found my pr bilibili plugin is in new appstore. But you may did wrong compile. The setting page is wrong(it 's not my app' s settings...).
My app settings is :

[https://github.com/awtrix/AWTRIX2.0-Apps/blob/master/bilibiliPlugin/bilibiliPlugin.bas#L29](https://github.com/awtrix/AWTRIX2.0-Apps/blob/master/bilibiliPlugin/bilibiliPlugin.bas#L29)

![image](https://user-images.githubusercontent.com/877939/56551717-adc26a00-65bb-11e9-838a-e0c5580fc994.png)

And the version wrong also. my app version is 1.0
So I think maybe your auto script compile and push plugin to app store has some errors.

**Comment by leeeboo** [comment]
And I am an youtuber in China. I made some videos for AWTRIX in Chinese:
https://youtu.be/ESAym1CUNIA
https://youtu.be/2Xe4PaCYtW4

**Comment by Blueforcer** [comment]
its not a bug, i change some important functions, so i needed to update every single app.
A huge update is comming next week

**Comment by leeeboo** [comment]
> its not a bug, i change some important functions, so i needed to update every single app.
> A huge update is comming next week

Okay, thanks.
Waiting for the update.
My friend ask me to use my bilibili plugin but found online version has error. So I just give him my compile version and waiting your updates next week.

**Comment by Blueforcer** [comment]
Can you tell me whats the error?

**Comment by leeeboo** [comment]
@Blueforcer Can you see the snapshot in this issue? The config page for bilibili plugin is wrong. I also write the error detail in that PR page.

**Comment by leeeboo** [comment]
@Blueforcer I think you may be use the new awtrix.bas overwrite my bilibiliPlugin.bas. Please see the snapshot above. Or you can just use my compiled version here: https://github.com/leeeboo/awtrix-bilibili/releases

**Comment by leeeboo** [comment]
@Blueforcer could you please make a correct version for my bilibili plugin on the AppStore ? Thank you very much!

**Comment by leeeboo** [comment]
@Blueforcer I find it is works ! I misunderstood it. Thank You!

I am working on several plugins for Chinese websites.
