### ISSUE TITLE
Twitch App - Follower and Viewer count

### ISSUE THREAD

**Issue by Locxion** [awtrix/AWTRIX2.0-Apps#14]
Twitch changed their API so the 1.0 Version doesnt work anymore.
Follower and Viewers Count is always 0

**Comment by Locxion** [comment]
AWtrix Log:
 {"error":"Gone","status":410,"message":"War. War never changes... but APIs do. See https://dev.twitch.tv/docs"}

**Comment by Blueforcer** [comment]
Fixed
https://github.com/awtrix/AWTRIX2.0-Apps/commit/9c28d8a558642a87bec927d3719b9cefff581fbc
