### ISSUE TITLE
Hello   Awtrix Java backend code repository is which

### ISSUE THREAD

**Issue by wujunze** [awtrix/AWTRIX2.0-Apps#19]
Hello 

Awtrix Java backend code repository is which ? 
Your project is great and interesting and I want to change some features

**Comment by wujunze** [comment]
@Blueforcer   Please See  Thanks

**Comment by Blueforcer** [comment]
the java host is closed source
https://awtrixdocs.blueforcer.de/#/en-en/host

**Comment by wujunze** [comment]
OK   how submit  an APP

**Comment by Blueforcer** [comment]
https://awtrixdocs.blueforcer.de/#/en-en/appreview
