### ISSUE TITLE
pm app

### ISSUE THREAD

**Issue by hanlihanshaobo** [awtrix/AWTRIX2.0-Apps#21]
When there are multiple options, the last item of openaq.org is displayed by default. For example, the last item of my corresponding position is SO2, and awtrix will display the value of SO2.Can not accurately display pm2.5 concentration

**Comment by romejiang** [comment]
#28 I submitted a PR, you try it

**Comment by Blueforcer** [comment]
merged in https://github.com/awtrix/AWTRIX2.0-Apps/commit/1fda7562b8f8a922e9bb52c40a19346a0b9c63f7
