### ISSUE TITLE
Crypto plugin is not the latest version

### ISSUE THREAD

**Issue by romejiang** [awtrix/AWTRIX2.0-Apps#29]
Hi，Blueforcer
version v1.1 in the app store, can you update the latest code here?

Thanks

**Comment by CWempe** [comment]
v1.1 is available in the Appstore.

But it is nor working.

You can install a working version by hand.
see: https://github.com/awtrix/AWTRIX2.0-Apps/issues/39

This issue could be closed, I guess.
