### ISSUE TITLE
[Matrix] NumberFormatException

### ISSUE THREAD

**Issue by CWempe** [awtrix/AWTRIX2.0-Apps#38]
I get "Critical Errors"  from the Matrix app.

![image](https://user-images.githubusercontent.com/1270359/158061103-931f9219-b546-400b-bc4a-a8c365b0ce5e.png)

```
  -->  14:12:40      Error while reading Matrix answer:
        (NumberFormatException) java.lang.NumberFormatException: For input string: "null"
```

The app still seems to work however.

**Comment by Blueforcer** [comment]
Seems like youre not running the same release state of host and controller. If youre running beta you need the beta controller.
btw. this is not the right place for host or matrix related stuff. Only apps.
