### ISSUE TITLE
[Crypto] not working (black screen)

### ISSUE THREAD

**Issue by CWempe** [awtrix/AWTRIX2.0-Apps#39]
The latest official Crypto app (v1.1) is not working.
You only get a black screen.

Elfish has fixed this by using another API.
You can download the `jar` file [here](https://discord.com/channels/546407049148366859/591247268263493632/942039848393515078) and copy it on your `Apps` folder and restart the Awtrix server.

But I think it would be great if this working version would be available via the Appstore.

**Comment by CWempe** [comment]
Could be a duplicate of https://github.com/awtrix/AWTRIX2.0-Apps/issues/36

**Comment by luisteam** [comment]
Thx for the fix

**Comment by luisteam** [comment]
> The latest official Crypto app (v1.1) is not working. You only get a black screen.
> 
> Elfish has fixed this by using another API. You can download the `jar` file [here](https://discord.com/channels/546407049148366859/591247268263493632/942039848393515078) and copy it on your `Apps` folder and restart the Awtrix server.
> 
> But I think it would be great if this working version would be available via the Appstore.

Hello, can you pass the link of the file from another source? Discord won't show me the file, thx

**Comment by Blueforcer** [comment]
updated with https://github.com/awtrix/AWTRIX2.0-Apps/commit/4636a4958b104b60a818106398cca0905c0187dc
